# Generated by Django 6.0.3 on 2026-03-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
