# Generated by Django 6.0.3 on 2026-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desctiption', models.CharField(max_length=500)),
                ('estimated_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='recipe',
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
