# Generated by Django 6.0.3 on 2026-03-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipies_delete_recipe_alter_ingridient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipies',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='recipies',
            name='estimated_time',
        ),
    ]
